CREATE TABLE Faculties (
	FacultyID int GENERATED ALWAYS
	AS IDENTITY UNIQUE NOT NULL,
	FacultyName text NOT NULL,
	Descript text NOT NULL
);

ALTER TABLE Faculties ADD CONSTRAINT
PKFaculties PRIMARY KEY (FacultyID);
